basePath: /
definitions:
  entity.Post:
    properties:
      id:
        type: integer
      text:
        type: string
      title:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: abc@gmail.com
    name: API Support
  description: This is a sample rest api to add and retrieve posts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Posts API
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: Get details of all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Post'
            type: array
      summary: Get details of all posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Add a new post
      parameters:
      - description: Create post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/entity.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Post'
      summary: Add a new post
      tags:
      - posts
swagger: "2.0"
